# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'realmApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'

  # Pods for realmApp

end
